### ISSUE TITLE
Bug Report: Quick start on amundsen raised some error.

### ISSUE THREAD

**Issue by rr-chiranjeevi-ds** [amundsen-io/amundsen#947] opened 2021-03-07 03:26 UTC
When following steps mentioned here https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker i got following error in connecting test tables itself 
 
 2021-03-07T03:19:26+0000.852 [ERROR] v0._get_table_metadata:149 (10:MainThread) - Encountered exception: {'columns': {0: {'col_type': ['Field may not be null.']}}}
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File "/app/amundsen_application/api/metadata/v0.py", line 143, in _get_table_metadata
amundsenfrontend    |     results_dict['tableData'] = marshall_table_full(table_data_raw)
amundsenfrontend    |   File "/app/amundsen_application/api/utils/metadata_utils.py", line 109, in marshall_table_full
amundsenfrontend    |     table: Table = schema.load(table_dict).data
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 588, in load
amundsenfrontend    |     result, errors = self._do_load(data, many, partial=partial, postprocess=True)
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 711, in _do_load
amundsenfrontend    |     raise exc
amundsenfrontend    | marshmallow.exceptions.ValidationError: {'columns': {0: {'col_type': ['Field may not be null.']}}}
amundsenfrontend    | 2021-03-07T03:19:26+0000.853 [DEBUG] action_log_callback.on_post_execution:70 (10:MainThread) - Calling callbacks: [<function logging_action_log at 0x7ff77f7c68c0>]

**Comment by feng-tao** [comment] 2021-03-07 05:54
similar issue as reported in https://github.com/amundsen-io/amundsen/issues/939 , we are looking into this.

**Comment by feng-tao** [comment] 2021-03-09 05:01
@dkunitsk has updated the docker compose script version. This issue should be fixed now.

**Closed by feng-tao** 2021-03-09 05:01 UTC
Labels: Type: Bug :beetle:

**Comment by sword0307** [comment] 2021-03-17 07:22
i meet the same wrong!
amundsenfrontend    | During handling of the above exception, another exception occurred:
amundsenfrontend    | 
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File "/app/amundsen_application/api/metadata/v0.py", line 63, in popular_tables
amundsenfrontend    |     response = request_metadata(url=url)
amundsenfrontend    |   File "/app/amundsen_application/api/utils/request_utils.py", line 46, in request_metadata
amundsenfrontend    |     data=data)
amundsenfrontend    |   File "/app/amundsen_application/api/utils/request_utils.py", line 112, in request_wrapper
amundsenfrontend    |     return s.get(url, headers=headers, timeout=timeout_sec)
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
amundsenfrontend    |     return self.request('GET', url, **kwargs)
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
amundsenfrontend    |     resp = self.send(prep, **send_kwargs)
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
amundsenfrontend    |     r = adapter.send(request, **kwargs)
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
amundsenfrontend    |     raise ConnectionError(e, request=request)
amundsenfrontend    | requests.exceptions.ConnectionError: HTTPConnectionPool(host='amundsenmetadata', port=5000): Max retries exceeded with url: /popular_tables/?limit=4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d31edec10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
amundsenfrontend    | 2021-03-17T07:17:16+0000.621 [DEBUG] connectionpool._new_conn:231 (10:MainThread) - Starting new HTTP connection (1): amundsenmetadata:5000
