### ISSUE TITLE
Bug Report (metadata) Tornado issue with Gremlin python client

### ISSUE THREAD

**Issue by jsnowacki** [amundsen-io/amundsen#1382] opened 2021-07-26 12:26 UTC
Running the latest version of [amundsen-metadata](https://hub.docker.com/r/amundsendev/amundsen-metadata/tags?page=1&ordering=last_updated), i.e. tak `latest` or `3.8.1` as they seem to be the same, I get the below error:

```python
2021-07-26T12:05:18+0000.682 [ERROR] app.log_exception:1761 (1:Thread-8) - Exception on /tags/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 87, in view
    self = view.view_class(*class_args, **class_kwargs)
  File "/app/metadata_service/api/tag.py", line 31, in __init__
    self.client = get_proxy_client()
  File "/app/metadata_service/proxy/__init__.py", line 47, in get_proxy_client
    client_kwargs=client_kwargs)
  File "/app/metadata_service/proxy/neptune_proxy.py", line 117, in __init__
    driver_remote_connection_options=driver_remote_connection_options)
  File "/app/metadata_service/proxy/gremlin_proxy.py", line 874, in __init__
    **_properties_except(self.driver_remote_connection_options, 'url'))
  File "/usr/local/lib/python3.7/site-packages/gremlin_python/driver/driver_remote_connection.py", line 45, in __init__
    password=password)
  File "/usr/local/lib/python3.7/site-packages/gremlin_python/driver/client.py", line 76, in __init__
    self._fill_pool()
  File "/usr/local/lib/python3.7/site-packages/gremlin_python/driver/client.py", line 92, in _fill_pool
    conn = self._get_connection()
  File "/usr/local/lib/python3.7/site-packages/gremlin_python/driver/client.py", line 105, in _get_connection
    self._transport_factory, self._executor, self._pool)
  File "/usr/local/lib/python3.7/site-packages/gremlin_python/driver/connection.py", line 40, in __init__
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/gremlin_python/driver/connection.py", line 45, in connect
    self._transport = self._transport_factory()
  File "/app/metadata_service/proxy/gremlin_proxy.py", line 873, in <lambda>
    transport_factory=lambda: TornadoTransport(read_timeout=None, write_timeout=None),
TypeError: __init__() got an unexpected keyword argument 'read_timeout'
```

I didn't see it before, metadata service worked and my code is not adding anything tornado or gremlin related. I'm using AWS Neptune but I'm not sure if it's related, as it seems that the code and tornado/gremlin client has a version mismatch. 

## Expected Behavior
Gremlin client should work fine.

## Current Behavior
As above.

## Possible Solution
Going back to 3.5.0 fixes it. I've only noticed it as we had previously `latest` tag used in our deployment.

## Steps to Reproduce
1. Deploy metadata service from Docker Hub image tag `3.8.1`.
2. Send get on `\tags\` endpoint; you should get status code 500.
3. See logs for error.

Note that if you have pods on k8s running, you need to delete them to pull new images.

## Screenshots (if appropriate)
NA

## Context
Metadata service doesn't work after version update. 

## Your Environment
* Amundsen version used: 3.8.1 (metadata-service
* Data warehouse stores: AWS Neptune as metadata service database
* Deployment (k8s or native): k8s
* Link to your fork or repository:

**Comment by feng-tao** [comment] 2021-08-05 02:03
@jsnowacki should be fixed now, feel free to reopen if it is not the case.

**Closed by feng-tao** 2021-08-05 02:03 UTC

**Comment by don-simpson** [comment] 2021-08-30 21:06
@feng-tao Not sure if this was confirmed to be fixed by @jsnowacki. Appears to still be an issue as of 3.9.0. I cloned and update my metadata/requirements.txt to use amundsen-gremlin>=0.0.12 and gremlinpython==3.4.12 and it seems to fix the issue.

**Comment by corrjo** [comment] 2021-09-03 17:58
Yeah I'm experiencing that same thing, this issue should probably be reopened.

**Comment by AykCanDem** [comment] 2021-12-01 21:20
I am getting the same error while using AWS Neptune as metadata service.

**Comment by AykCanDem** [comment] 2022-04-11 19:05
I didnt because I used Neo4j.

**Comment by jorgebaez212** [comment] 2022-04-26 21:43
Hi @feng-tao, after several tests, I realized that this error happens because `/app/metadata_service/proxy/gremlin_proxy.py`
is trying to generate a `TornadoTransport(read_timeout=None, write_timeout=None)` with parameters that gremlinpython==3.4.3 doesn't support.

Running a `pip install gremlinpython==3.4.13` in the `amundsendev/amundsen-metadata:3.10.0` image solves the error, but while building this new modified image, the following error appears:
`amundsen-metadata 3.10.0 requires gremlinpython==3.4.3, but you have gremlinpython 3.4.13 which is incompatible.`

I haven't really seen any other dependencies/issues appearing on the image after the change but I might be missing something.. 

Do you think it could be possible to change the gremlinpython requirement or at least change the version for a new one that implements the parameters used on the TornadoTransport call? (I think the first one that implements these parameters is  [gremlinpython==3.4.9](https://github.com/apache/tinkerpop/blob/3.4.9/gremlin-python/src/main/jython/gremlin_python/driver/tornado/transport.py)

Would it be enough to change the [setup.py](https://github.com/amundsen-io/amundsen/blob/main/metadata/setup.py) gremlinpython requirement (line 30/31), or should we change it somewhere else?

**Comment by ggirodda** [comment] 2022-06-25 09:29
This is still a problem when using the last amundsen metadata docker image (3.10.0) with neptune proxy.

**Comment by shahinism** [comment] 2023-03-16 08:39
The same issue is still available on the master branch. The official `amundsendev/amundsen-metadata:3.11.0` is not shipping `amundsen_gremlin` package, thus [this happens](https://github.com/amundsen-io/amundsen/blob/da1ca581cfe4a78af7d6cee86c66a272cb6ca241/metadata/metadata_service/config.py#L174). Building a container with installed installs `gremlinpython==3.4.3` which suffers the same issue as mentioned on this issue.
