### ISSUE TITLE
Amundsen Docker Environment Configuration Failing

### ISSUE THREAD

**Issue by vthorwat** [amundsen-io/amundsen#823] opened 2020-11-30 10:46 UTC
Hello All,

I am new to the Amundsen environment, I am trying to configure amundsen with Apache atlas as backend.

I am following below installation steps from Link: 

**LInk : https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md**

While installing this in our environment I am facing issue as below :  

```
[root@jbdlcanary amundsen]# docker-compose -f docker-amundsen-atlas.yml up
Building amundsensearch
Step 1/8 : FROM python:3.7-slim
 ---> fb940aff3fbd
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> 76aa5ef98ef4
Step 3/8 : RUN pip3 install gunicorn
 ---> Running in 73d340496dcf
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fac85810d10>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/gunicorn/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fac85758390>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/gunicorn/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fac8541d690>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/gunicorn/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fac858241d0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/gunicorn/

```
It is just stuck out here. Is this due to some proxy issue that docker could not able to run pip command inside the container?

Please suggest if you have some idea about this.

Thanks in Advance.,
Vinod Thorwat

**Comment by jornh** [comment] 2020-11-30 13:56
> It is just stuck out here. Is this due to some proxy issue that docker could not able to run pip command inside the container?

Yes that's very likely. Check from within a container on the given host that you are able to e.g. run this 

```
curl https://pypi.org/simple/gunicorn/
```

If that's somehow blocked you will have a hard time evaluating Amundsen in that environment.

**Comment by coolgooze** [comment] 2020-11-30 15:54
It was indeed Proxy. We applied Proxy on the DockerFiles to get over this..

**Comment by jornh** [comment] 2020-12-01 08:58
@vthorwat does this mean the issue is resolved so you can close it?

**Comment by feng-tao** [comment] 2020-12-02 06:07
thanks @jornh for the debugging! @coolgooze @vthorwat feel free to reopen if the issue remains.

**Closed by feng-tao** 2020-12-02 06:07 UTC
