### ISSUE TITLE
bug: Editing column descriptions does not work

### ISSUE THREAD

**Issue by jonhehir** [amundsen-io/amundsen#558] opened 2020-07-13 19:15 UTC
It looks like this may be a recent regression.

## Expected Behavior

When `is_editable` is `true`, there are two conditions:

- if the column already has a description, there should be an icon/link to edit the description
- if the column does not have a description, the "Add Description" link should open a textbox to edit the description

## Current Behavior

- For a column with a description, no edit icon/link appears.
- For a column with no description, the "Add Description" link appears, but clicking it does nothing and triggers a JS error (see screenshot).

## Steps to Reproduce

1. `docker-compose -f docker-compose-local.yml up`
2. Edit the sample data in `amundsendatabuilder/example/sample_data` to include a column with no description. (Currently all example columns have descriptions.)
3. Attempt to add/edit descriptions.

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/745011/87343557-0a8ca600-c51b-11ea-9b14-ad573ba4cb44.png)

![image](https://user-images.githubusercontent.com/745011/87343934-99012780-c51b-11ea-9284-634ac7e2dfac.png)

![image](https://user-images.githubusercontent.com/745011/87343951-9e5e7200-c51b-11ea-81ea-4a9242142f59.png)

## Your Environment

`docker-amundsen-local.yml` using current versions as of writing (7/13).

**Comment by dikshathakur3119** [comment] 2020-07-13 20:11
Hi Jonathan,

Thank you for raising this issue, but I am not able to recreate this on my end. Column Description is working fine for me in both scenarios, when `is_editable` is `True` or `False`.  I searched about the error you are encountering `Unknown Props`, it may arise due to use of function `React.cloneElement` which we are using [https://github.com/lyft/amundsenfrontendlibrary/blob/master/amundsen_application/static/js/components/common/EditableSection/index.tsx#L112](here) and child component is a DOM (not React Component). Please see if you have made nay change related to this on your local.

**Comment by jonhehir** [comment] 2020-07-13 22:22
Hi, Diksha! Thanks for the quick response. Here are more detailed instructions on how I am experiencing this issue:

First, check out `master` for `amundsen`. I have a clean local install with no changes.

```[master] ~/amundsen: git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

[master] ~/amundsen: git submodule status
 7ea1e5ea2b1be6687c322cbc71f6156d4db08bca amundsencommon (0.3.6)
 496ddfe6b6f17eaec477b67892a7073dd9efa9b5 amundsendatabuilder (2.6.4-5-g496ddfe)
 f7de1e81f14b0d00f2e15f48339f3640a54b0c22 amundsenfrontendlibrary (v2.2.0-9-gf7de1e8)
 5a8c1170358cbfb56b7d9341c4c519815e3cbdbb amundsenmetadatalibrary (v2.5.4-4-g5a8c117)
 6ae8194f9344e792c884b2763723de0f83199d81 amundsensearchlibrary (2.4.0-2-g6ae8194)
```

For the sake of testing, add a column to one of the test tables that has no description:

```[master] ~/amundsen: echo 'col2,,"int",2,hive,gold,test_schema,test_table3' >> amundsendatabuilder/example/sample_data/sample_col.csv```

Using `docker-amundsen-local.yml`, re-build and launch Amundsen:

```
[master] ~/amundsen: docker-compose -f docker-amundsen-local.yml build
[master] ~/amundsen: docker-compose -f docker-amundsen-local.yml up
```

Then import the (modified) sample data using the sample loader:

```
(amundsen) [master] ~/amundsen: cd amundsendatabuilder/
(amundsen) [HEAD] ~/amundsen/amundsendatabuilder: python example/scripts/sample_data_loader.py
```

Then go to http://localhost:5000/table_detail/gold/hive/test_schema/test_table3. The first column description is uneditable, and the second column has no description. Trying to add a description triggers the above error.

Let me know if these instructions work for reproducing the error.

**Comment by ttannis** [comment] 2020-07-14 21:02
@jonhehir are you able to verify that the code your are running using this setup is using the latest master? I'm unable to reproduce this as well and I'm unsure if perhaps the docker setup is doing something unintended?

Is it also possible that your browser itself is running a version of the app with cached code after you rebuilt. Does it reproduce if you do a hard refresh in your browser?

**Comment by jonhehir** [comment] 2020-07-14 21:26
Huh, that's strange. Here's what I'm looking at in terms of git revisions. They match what I'm currently seeing in GitHub:

```
[master] ~/amundsen: git rev-parse HEAD
9fb94ab5aa04b447448c6949d5977679742d4d0e
[master] ~/amundsen: git submodule status
 7ea1e5ea2b1be6687c322cbc71f6156d4db08bca amundsencommon (0.3.6)
 496ddfe6b6f17eaec477b67892a7073dd9efa9b5 amundsendatabuilder (2.6.4-5-g496ddfe)
 f7de1e81f14b0d00f2e15f48339f3640a54b0c22 amundsenfrontendlibrary (v2.2.0-9-gf7de1e8)
 5a8c1170358cbfb56b7d9341c4c519815e3cbdbb amundsenmetadatalibrary (v2.5.4-4-g5a8c117)
 6ae8194f9344e792c884b2763723de0f83199d81 amundsensearchlibrary (2.4.0-2-g6ae8194)
```

I've tried a hard refresh in Chrome, Chrome incognito, and Firefox private. All show the same behavior, so it doesn't seem to be a caching issue.

While the instructions I have here are for the docker-compose setup for local testing, we are also seeing this issue on an actual in-house Amundsen deployment, which is using a modified version of the Dockerfile from amundsenfrontendlibrary@f7de1e81f14b0d00f2e15f48339f3640a54b0c22.

**Comment by dorianj** [comment] 2020-11-12 19:37
@jonhehir are you still seeing this?

**Comment by jonhehir** [comment] 2020-11-12 20:34
Unfortunately, I have not been working on this project recently. @jdavidheiser: Is this still an issue for you guys?

**Comment by jdavidheiser** [comment] 2020-11-12 21:14
I was not able to reproduce this bug on our Amundsen instance.

**Comment by feng-tao** [comment] 2020-11-12 21:47
I think the issue has already been fixed by @dikshathakur3119  before which we could close this issue now.

**Closed by feng-tao** 2020-11-12 21:47 UTC
Labels: Project: Frontend, Status: Review Needed, Type: Bug :beetle:, keep fresh
