### ISSUE TITLE
sample_glue_loader returns 'Something went wrong...' on the front-end

### ISSUE THREAD

**Issue by eponkratova** [amundsen-io/amundsen#881] opened 2021-01-17 17:57 UTC
## Expected Behavior
Glue tables metadata is displayed on the front-end

## Current Behavior
On the front-end, I see 'Something went wrong...'

## Steps to Reproduce
I am running Amundsen on my local machine:
1. followed the installation guide at https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md, including the required python libraries.
2. modified sample_glue_loader and added aws session token.
3. when I opened the front-end, the tables from Glue were listed but when I click any, the error displayed 'Something went wrong...' . The example of the URL of one of the tables (iriscsv) located in in the iris database is:
http://localhost:5000/table_detail/AWSSessionToken=%22/glue/iris/iriscsv.

## Context
I am doing a POC.

**Comment by feng-tao** [comment] 2021-01-22 06:23
do you verify the table is ingested into neo4j correctly with neo4j UI?

**Comment by eponkratova** [comment] 2021-01-23 07:42
I can see the tables on neo4j, when I switch to the table view, I see the similar content for all tables retrieved:
{
  "name": "test_table1",
  "publisher_last_updated_epoch_ms": 1610954798471,
  "published_tag": "unique_tag",
  "key": "hive://gold.test_schema/test_table1",
  "is_view": false
}

**Comment by OElesin** [comment] 2021-01-30 09:23
I'm experiencing the same thing as well. Any help here

**Comment by eponkratova** [comment] 2021-01-31 00:41
OElesin, check the Athena one if you need to get crawl the s3 data. If you use Python, not Airflow, I slightly modified the original code at https://github.com/eponkratova/articles/blob/master/data_discovery/code/athena_data_loader.py

**Comment by OElesin** [comment] 2021-01-31 15:16
@eponkratova, I tried this and got the same error. This is quite surprising

**Comment by OElesin** [comment] 2021-01-31 15:27
From the error logs

```python
self.client = get_proxy_client()
--
File "/usr/local/lib/python3.7/site-packages/amundsen_metadata-3.0.1-py3.7.egg/metadata_service/proxy/__init__.py", line 47, in get_proxy_client
client_kwargs=client_kwargs)
TypeError: __init__() got an unexpected keyword argument 'client_kwargs'
```

**Comment by OElesin** [comment] 2021-01-31 16:07
@feng-tao and @eponkratova, the issue is likely due to recent changes in the metadata library. I reverted the image being used to `amundsen-metadata:3.0.0` and everything seems to be fixed.

Looks like this is from: https://github.com/amundsen-io/amundsenmetadatalibrary/blob/master/metadata_service/proxy/__init__.py#L47

**Comment by eponkratova** [comment] 2021-02-01 03:37
@OElesin , so, did you make the Glue connector working as well?

**Comment by OElesin** [comment] 2021-02-01 04:21
@eponkratova, both are working.

**Comment by eponkratova** [comment] 2021-02-01 05:00
Aha, thank you, @OElesin

**Comment by feng-tao** [comment] 2021-02-01 05:06
cc @mgorsk1

**Comment by NiravLangaliya** [comment] 2021-02-04 14:05
I have installed new code and I am also facing the same issue and it complains about 

`TypeError: __init__() got an unexpected keyword argument 'client_kwargs'`

**Comment by feng-tao** [comment] 2021-02-04 16:56
@mgorsk1 could you take a look?

**Comment by mgorsk1** [comment] 2021-02-04 17:53
sure, looking into it

**Comment by mgorsk1** [comment] 2021-02-04 19:33
apologies, that's my blunder. I've submitted fix https://github.com/amundsen-io/amundsenmetadatalibrary/pull/258 any chance you can verify if that helped @OElesin @eponkratova

**Comment by feng-tao** [comment] 2021-02-04 21:37
no worry, @mgorsk1 's change (https://github.com/amundsen-io/amundsenmetadatalibrary/pull/258) is just merged. @NiravLangaliya could you pull from master and see if the issue is gone?

**Comment by feng-tao** [comment] 2021-02-05 05:05
Feel free to reopen if the issue persists after pulling from master.

**Closed by feng-tao** 2021-02-05 05:05 UTC
Labels: Project: Metadata, Type: Bug :beetle:

**Comment by cpollard0** [comment] 2021-08-28 01:39
@feng-tao - I'm getting the same issue now with loading Glue data. I'm on the latest branch from master, my data is in neo4j. When I click on a table in the WebUI I get 404 not found. Any guidance would be appreciated!
